### ISSUE TITLE
Use of closures is preventing serialization

### ISSUE THREAD

**Issue by oucil** [PhpUnitsOfMeasure/php-units-of-measure#33] opened 2015-01-12 21:08 UTC
There's a problem with your `HasSIUnitsTrait` class that effectively renders the entire class useless when serialization is required, unless we take the extra steps to write `__sleep()` and `__wakeup()` methods for every object in our system that we want to use your classes in.  

Closures can not be serialized, and our use case is in a shipping system where we need to be able to cache (via serialization) our objects so we don't have to continually repeat API calls during each request.

However line 166 of `HasSIUnitsTrait`....
```
$parsePattern = function ($pattern) use ($prefixDefinition) {...}
```
... and the ensuing code, is incompatible and causing fatal errors.

Any suggestions to avoid having to use `__sleep()` and `__wakeup()` everywhere?

**Comment by triplepoint** [comment] 2015-01-14 00:42
Hunh, that's a new one. I guess I don't serialize() objects that often; never noticed this issue.

I don't think that particular closure is core to the functionality of that trait; I mostly used that pattern there to avoid polluting the interfaces of classes that use this trait with an extra parsePattern() method.  It'd be easy enough to resolve this issue by replacing the lambda with a named method.

It makes me wonder where else this is an issue in this library.  I should probably add serialize() and unserialize() functional tests to cover this case.

**Comment by triplepoint** [comment] 2015-01-15 03:23
So I added tests for serialize and unserialize, and they pass
https://github.com/triplepoint/php-units-of-measure/commit/0cb19dd984d377d60910338334406d6546b32792
https://travis-ci.org/triplepoint/php-units-of-measure/builds/47073026

Can you give some example code that fails, and which php version it fails on?

**Comment by ecommunities** [comment] 2015-01-15 17:45
Thanks for trying to source the problem so quickly, appreciate the effort!  I'll have to look at what's happening in the tests a little closer, but I can reproduce with something as simple as:
```
$width = new Length(12.0,'in');
serialize($width);
```
The resulting error message is...
```
Uncaught exception 'Exception' with message 'Serialization of 'Closure' is not allowed' in...
```
Our dev box is a Windows machine running Zend Server 6.3, PHP Version 5.5.7

**Comment by triplepoint** [comment] 2015-01-15 19:27
Interesting, I'll see if I can reproduce it this evening.

**Comment by ecommunities** [comment] 2015-01-15 19:31
BTW, I should point out that we've worked around this so no rush.  Treat this as a nice-to-have rather than a must.

Cheers!

**Comment by triplepoint** [comment] 2015-01-17 23:23
I created a test case running the exact code above, and couldn't reproduce this issue.  

My test environment was a stock virtual machine running Ubuntu precise64, with PHP version 5.5.15.  Combined with the previous similar tests running on various environments under Travis (see the links above), I'm pretty much stumped.  Maybe Windows has a different behavior?  Maybe there's some other feature of your environment that causes this issue?

I'll leave the ticket open in case anyone down the road wants to take a swing at resolving this issue.

**Comment by triplepoint** [comment] 2016-02-21 08:29
Closing, we never found the root cause of the reported issue.  Maybe it was a windows vs linux thing?

**Closed by triplepoint** 2016-02-21 08:29 UTC
